apiVersion: v1
kind: Service
metadata:
  labels:
    app: ic-sample-api
  name: ic-sample-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  selector:
    app: ic-sample-api
